import React, { useState, useEffect } from 'react'
import { Loader, Card, FormField } from '../components'

const Home = () => {

  const [loading, setLoading] = useState(false);
  const [allPosts, setAllPosts] = useState(null);
  const [searchTerm, setSearchTerm] = useState('popcorn');

  return (
    <section className='max-w-7xl mx-auto'>
      <div>
        <h1 className='font-extrabold text-[#2222328] text-[35px]'>
          The Community Showcase 
        </h1>
        <p className='mt-2 text-[#666e75] text-[14px] max-w [500px]'>
            Browse though a collection of the best posts from the community, generated by DALL-E AI.
        </p>
      </div>
      <div className='mt-16'>
        <FormField />
      </div>
      <div className='mt-10'>
      {loading ? (
        <div className='flex justify-center items-center'>
          <Loader />
        </div>
      ) : (
        <>
          {searchTerm  && (
            <h2 className='font-medium text-[#666e75] text-xl mb-3'>
              Search Results for <span className='text-[#222328]'> {searchTerm} </span>
            </h2>
          )}
        
        </>
      )}
      </div>
    </section>
  )
}

export default Home